// ---------------------------------------------------------------------------
// Nationality-aware name pools
// ---------------------------------------------------------------------------

pub(super) struct NationalityNames {
    pub nationality: &'static str,
    pub first_names: &'static [&'static str],
    pub last_names: &'static [&'static str],
}

pub(super) const NATIONALITY_POOLS: &[NationalityNames] = &[
    NationalityNames {
        nationality: "ENG",
        first_names: &[
            "James", "Harry", "Jack", "Oliver", "George", "Charlie", "Thomas", "William", "Daniel",
            "Ben", "Luke", "Ryan", "Sam", "Callum", "Nathan", "Adam", "Liam", "Marcus", "Ethan",
            "Mason",
        ],
        last_names: &[
            "Smith", "Johnson", "Brown", "Jones", "Taylor", "Wilson", "Walker", "Robinson",
            "Clark", "Wright", "Hall", "Green", "Baker", "Hill", "Allen", "Young", "King",
            "Cooper", "Parker", "Turner",
        ],
    },
    NationalityNames {
        nationality: "SCO",
        first_names: &[
            "Jack", "Lewis", "Fraser", "Ross", "Callum", "Scott", "Ryan", "Ewan", "Craig",
            "Stuart", "Cameron", "Kieran", "Jamie", "Gregor", "Finlay", "Liam", "Arran", "Declan",
            "Blair", "Dylan",
        ],
        last_names: &[
            "McDonald",
            "Stewart",
            "Robertson",
            "Campbell",
            "Anderson",
            "Scott",
            "Reid",
            "Murray",
            "Ross",
            "Paterson",
            "Ferguson",
            "MacLeod",
            "Johnston",
            "Morrison",
            "Walker",
            "Bell",
            "Fraser",
            "Clark",
            "Sutherland",
            "Graham",
        ],
    },
    NationalityNames {
        nationality: "WAL",
        first_names: &[
            "Rhys", "Dylan", "Owain", "Gethin", "Harri", "Cai", "Ioan", "Evan", "Morgan", "Ellis",
            "Tomos", "Aneurin", "Lloyd", "Osian", "Jac", "Ieuan", "Bryn", "Steffan", "Carwyn",
            "Gruffydd",
        ],
        last_names: &[
            "Jones",
            "Williams",
            "Davies",
            "Evans",
            "Thomas",
            "Roberts",
            "Lewis",
            "Morgan",
            "Griffiths",
            "Hughes",
            "Price",
            "Rees",
            "Jenkins",
            "Owen",
            "Lloyd",
            "Edwards",
            "Pritchard",
            "Powell",
            "Vaughan",
            "Parry",
        ],
    },
    NationalityNames {
        nationality: "NIR",
        first_names: &[
            "Conor", "Ryan", "Niall", "Ciaran", "Eoin", "Sean", "Darragh", "Ronan", "Cathal",
            "Paddy", "Shane", "Rory", "Callum", "Odhran", "Aidan", "Ethan", "Johnny", "Reece",
            "Aaron", "Daniel",
        ],
        last_names: &[
            "McCann",
            "O'Neill",
            "Murphy",
            "Doherty",
            "McLaughlin",
            "Quinn",
            "McKenna",
            "Gallagher",
            "Devlin",
            "Maguire",
            "Boyle",
            "McAllister",
            "McBride",
            "McCormick",
            "Campbell",
            "McGrath",
            "Mullan",
            "Morrow",
            "Moore",
            "Lavery",
        ],
    },
    NationalityNames {
        nationality: "IE",
        first_names: &[
            "Sean", "Conor", "Cian", "Darragh", "Oisin", "Padraig", "Tadhg", "Eoin", "Ronan",
            "Fionn", "Cillian", "Brian", "Aidan", "Shane", "Diarmuid", "Niall", "Ruairi", "Cathal",
            "Liam", "Jack",
        ],
        last_names: &[
            "Murphy",
            "Kelly",
            "Byrne",
            "Ryan",
            "O'Brien",
            "Walsh",
            "Doyle",
            "McCarthy",
            "Gallagher",
            "Kennedy",
            "Lynch",
            "Murray",
            "Quinn",
            "Moore",
            "Dunne",
            "Carroll",
            "Connolly",
            "Sullivan",
            "Brennan",
            "Power",
        ],
    },
    NationalityNames {
        nationality: "GB",
        first_names: &[
            "James", "Harry", "Jack", "Oliver", "George", "Charlie", "Thomas", "William", "Daniel",
            "Ben", "Luke", "Ryan", "Joe", "Sam", "Callum", "Nathan", "Ross", "Adam", "Liam",
            "Marcus",
        ],
        last_names: &[
            "Smith", "Johnson", "Williams", "Brown", "Jones", "Taylor", "Wilson", "Davies",
            "Evans", "Walker", "Robinson", "Clark", "Wright", "Hall", "Green", "Baker", "Hill",
            "Allen", "Young", "King",
        ],
    },
    NationalityNames {
        nationality: "ES",
        first_names: &[
            "Sergio",
            "Pablo",
            "Alejandro",
            "Carlos",
            "Javier",
            "Miguel",
            "Raul",
            "David",
            "Andres",
            "Alvaro",
            "Hugo",
            "Iker",
            "Marcos",
            "Luis",
            "Pedro",
            "Adrian",
            "Diego",
            "Fernando",
            "Gonzalo",
            "Antonio",
        ],
        last_names: &[
            "Garcia",
            "Rodriguez",
            "Martinez",
            "Lopez",
            "Sanchez",
            "Fernandez",
            "Gonzalez",
            "Hernandez",
            "Moreno",
            "Ruiz",
            "Diaz",
            "Alvarez",
            "Romero",
            "Torres",
            "Navarro",
            "Gil",
            "Vega",
            "Ramos",
            "Ortiz",
            "Castro",
        ],
    },
    NationalityNames {
        nationality: "DE",
        first_names: &[
            "Lukas",
            "Niklas",
            "Leon",
            "Felix",
            "Maximilian",
            "Jonas",
            "Florian",
            "Julian",
            "Tim",
            "Jan",
            "Kevin",
            "Marco",
            "Kai",
            "Stefan",
            "Patrick",
            "Dennis",
            "Tobias",
            "Marcel",
            "Timo",
            "Lars",
        ],
        last_names: &[
            "Müller",
            "Schmidt",
            "Schneider",
            "Fischer",
            "Weber",
            "Meyer",
            "Wagner",
            "Becker",
            "Schulz",
            "Hoffmann",
            "Koch",
            "Richter",
            "Wolf",
            "Schäfer",
            "Neumann",
            "Schwarz",
            "Zimmermann",
            "Braun",
            "Hartmann",
            "Krüger",
        ],
    },
    NationalityNames {
        nationality: "FR",
        first_names: &[
            "Antoine",
            "Hugo",
            "Lucas",
            "Mathieu",
            "Julien",
            "Maxime",
            "Pierre",
            "Thomas",
            "Raphael",
            "Adrien",
            "Kevin",
            "Alexandre",
            "Nicolas",
            "Loic",
            "Clement",
            "Florian",
            "Theo",
            "Damien",
            "Yann",
            "Baptiste",
        ],
        last_names: &[
            "Martin", "Bernard", "Dubois", "Thomas", "Robert", "Petit", "Moreau", "Laurent",
            "Simon", "Michel", "Lefevre", "Leroy", "Roux", "David", "Bertrand", "Morel",
            "Fournier", "Girard", "Bonnet", "Dupont",
        ],
    },
    NationalityNames {
        nationality: "IT",
        first_names: &[
            "Marco",
            "Luca",
            "Andrea",
            "Matteo",
            "Alessandro",
            "Lorenzo",
            "Davide",
            "Simone",
            "Riccardo",
            "Federico",
            "Gianluca",
            "Stefano",
            "Fabio",
            "Roberto",
            "Nicola",
            "Salvatore",
            "Daniele",
            "Paolo",
            "Vincenzo",
            "Emanuele",
        ],
        last_names: &[
            "Rossi", "Russo", "Ferrari", "Esposito", "Bianchi", "Romano", "Colombo", "Ricci",
            "Marino", "Greco", "Bruno", "Gallo", "Conti", "De Luca", "Costa", "Mancini",
            "Barbieri", "Fontana", "Santoro", "Rinaldi",
        ],
    },
    NationalityNames {
        nationality: "NL",
        first_names: &[
            "Daan", "Sem", "Lars", "Tim", "Thomas", "Jesse", "Jordi", "Luuk", "Rick", "Bas",
            "Stijn", "Nick", "Davy", "Wesley", "Kevin", "Robin", "Sander", "Ruud", "Dennis",
            "Patrick",
        ],
        last_names: &[
            "De Jong",
            "Van Dijk",
            "Jansen",
            "De Vries",
            "Van den Berg",
            "Bakker",
            "Visser",
            "Smit",
            "Meijer",
            "De Boer",
            "Mulder",
            "Dekker",
            "Peters",
            "Hendriks",
            "Van Leeuwen",
            "De Graaf",
            "Kok",
            "Brouwer",
            "Vermeer",
            "Van Dam",
        ],
    },
    NationalityNames {
        nationality: "PT",
        first_names: &[
            "Rui", "Joao", "Bruno", "Diogo", "Pedro", "Tiago", "Nuno", "Miguel", "Andre",
            "Goncalo", "Rafael", "Luis", "Ricardo", "Hugo", "Fabio", "Bernardo", "Daniel", "Vitor",
            "Nelson", "Sergio",
        ],
        last_names: &[
            "Silva",
            "Santos",
            "Ferreira",
            "Costa",
            "Pereira",
            "Oliveira",
            "Rodrigues",
            "Martins",
            "Sousa",
            "Fernandes",
            "Goncalves",
            "Lopes",
            "Almeida",
            "Carvalho",
            "Ribeiro",
            "Pinto",
            "Teixeira",
            "Mendes",
            "Neves",
            "Vieira",
        ],
    },
    NationalityNames {
        nationality: "BR",
        first_names: &[
            "Lucas",
            "Gabriel",
            "Rafael",
            "Matheus",
            "Guilherme",
            "Felipe",
            "Thiago",
            "Vinicius",
            "Pedro",
            "Gustavo",
            "Bruno",
            "Leonardo",
            "Anderson",
            "Douglas",
            "Eduardo",
            "Henrique",
            "Marcelo",
            "Diego",
            "Igor",
            "Leandro",
        ],
        last_names: &[
            "Silva",
            "Santos",
            "Oliveira",
            "Souza",
            "Pereira",
            "Costa",
            "Ferreira",
            "Rodrigues",
            "Almeida",
            "Nascimento",
            "Lima",
            "Araujo",
            "Ribeiro",
            "Carvalho",
            "Gomes",
            "Martins",
            "Rocha",
            "Mendes",
            "Barbosa",
            "Moreira",
        ],
    },
    NationalityNames {
        nationality: "AR",
        first_names: &[
            "Lionel", "Gonzalo", "Angel", "Sergio", "Nicolas", "Pablo", "Mauro", "Lucas",
            "Ezequiel", "Javier", "Marcos", "Leandro", "Federico", "Ignacio", "Rodrigo", "Matias",
            "Franco", "Agustin", "Julian", "Cristian",
        ],
        last_names: &[
            "Gonzalez",
            "Rodriguez",
            "Martinez",
            "Lopez",
            "Fernandez",
            "Garcia",
            "Romero",
            "Diaz",
            "Torres",
            "Sanchez",
            "Alvarez",
            "Acosta",
            "Gutierrez",
            "Castro",
            "Pereyra",
            "Aguero",
            "Ruiz",
            "Herrera",
            "Medina",
            "Flores",
        ],
    },
    NationalityNames {
        nationality: "BE",
        first_names: &[
            "Kevin", "Eden", "Romelu", "Dries", "Yannick", "Thomas", "Axel", "Thorgan", "Michy",
            "Nacer", "Radja", "Jan", "Toby", "Simon", "Leander", "Jason", "Timothy", "Hans",
            "Dennis", "Laurent",
        ],
        last_names: &[
            "Janssens", "Peeters", "Maes", "Jacobs", "Mertens", "Willems", "Claes", "Goossens",
            "Wouters", "De Smet", "Hermans", "Peters", "Stevens", "Leclercq", "Lambert", "Dupont",
            "Dumont", "Simon", "Laurent", "Renard",
        ],
    },
    NationalityNames {
        nationality: "HR",
        first_names: &[
            "Luka", "Ivan", "Mateo", "Mario", "Dejan", "Ante", "Josip", "Marko", "Nikola",
            "Marcelo", "Andrej", "Darijo", "Sime", "Borna", "Domagoj", "Vedran", "Duje", "Filip",
            "Tin", "Bruno",
        ],
        last_names: &[
            "Kovacic",
            "Horvat",
            "Babic",
            "Maric",
            "Juric",
            "Novak",
            "Perisic",
            "Tomic",
            "Vucinic",
            "Brozovic",
            "Kramaric",
            "Vidovic",
            "Lovren",
            "Srna",
            "Rakitic",
            "Modric",
            "Pasalic",
            "Rebic",
            "Livakovic",
            "Gvardiol",
        ],
    },
    NationalityNames {
        nationality: "SE",
        first_names: &[
            "Emil",
            "Oscar",
            "Viktor",
            "Erik",
            "Alexander",
            "Marcus",
            "Sebastian",
            "Filip",
            "Albin",
            "Robin",
            "Pontus",
            "Mattias",
            "Andreas",
            "Gustav",
            "Kristoffer",
            "Joel",
            "Ludwig",
            "Simon",
            "Martin",
            "Henrik",
        ],
        last_names: &[
            "Andersson",
            "Johansson",
            "Karlsson",
            "Nilsson",
            "Eriksson",
            "Larsson",
            "Olsson",
            "Persson",
            "Svensson",
            "Gustafsson",
            "Pettersson",
            "Jonsson",
            "Jansson",
            "Hansson",
            "Bengtsson",
            "Lindberg",
            "Lundqvist",
            "Forsberg",
            "Lindqvist",
            "Berg",
        ],
    },
];

// ---------------------------------------------------------------------------
// Team data — 16 teams across multiple countries
// ---------------------------------------------------------------------------

pub(super) struct PlayerRosterEntry {
    pub first_name: &'static str,
    pub last_name: &'static str,
    pub nationality: &'static str,
    pub position: &'static str,
}

const fn gk(f: &'static str, l: &'static str, n: &'static str) -> PlayerRosterEntry {
    PlayerRosterEntry { first_name: f, last_name: l, nationality: n, position: "Goalkeeper" }
}
const fn def(f: &'static str, l: &'static str, n: &'static str) -> PlayerRosterEntry {
    PlayerRosterEntry { first_name: f, last_name: l, nationality: n, position: "Defender" }
}
const fn mid(f: &'static str, l: &'static str, n: &'static str) -> PlayerRosterEntry {
    PlayerRosterEntry { first_name: f, last_name: l, nationality: n, position: "Midfielder" }
}
const fn fwd(f: &'static str, l: &'static str, n: &'static str) -> PlayerRosterEntry {
    PlayerRosterEntry { first_name: f, last_name: l, nationality: n, position: "Forward" }
}

pub(super) struct TeamTemplate {
    pub name: &'static str,
    pub short_name: &'static str,
    pub city: &'static str,
    pub country: &'static str,
    pub colors: (&'static str, &'static str),
    pub play_style: &'static str,
    pub stadium_name: &'static str,
    pub roster: &'static [PlayerRosterEntry],
}

pub(super) const TEAM_TEMPLATES: &[TeamTemplate] = &[
    TeamTemplate {
        name: "Arsenal",
        short_name: "ARS",
        city: "London",
        country: "England",
        colors: ("#dc2626", "#ffffff"),
        play_style: "Possession",
        stadium_name: "Emirates Stadium",
        roster: &[
            gk("David", "Raya", "ES"),
            gk("Karl", "Hein", "EE"),
            def("William", "Saliba", "FR"),
            def("Gabriel", "Magalhaes", "BR"),
            def("Ben", "White", "ENG"),
            def("Jurrien", "Timber", "NL"),
            def("Cristhian", "Mosquera", "CO"),
            def("Riccardo", "Calafiori", "IT"),
            def("Oleksandr", "Zinchenko", "UA"),
            mid("Declan", "Rice", "ENG"),
            mid("Martin", "Odegaard", "NO"),
            mid("Mikel", "Merino", "ES"),
            mid("Martin", "Zubimendi", "ES"),
            mid("Christian", "Norgaard", "DK"),
            mid("Ethan", "Nwaneri", "ENG"),
            mid("Myles", "Lewis-Skelly", "ENG"),
            fwd("Bukayo", "Saka", "ENG"),
            fwd("Gabriel", "Martinelli", "BR"),
            fwd("Viktor", "Gyokeres", "SE"),
            fwd("Leandro", "Trossard", "BE"),
            fwd("Noni", "Madueke", "ENG"),
            fwd("Jakub", "Kiwior", "PL"),
        ],
    },
    TeamTemplate {
        name: "Manchester City",
        short_name: "MCI",
        city: "Manchester",
        country: "England",
        colors: ("#60a5fa", "#1e3a5f"),
        play_style: "Attacking",
        stadium_name: "Etihad Stadium",
        roster: &[
            gk("Gianluigi", "Donnarumma", "IT"),
            gk("James", "Trafford", "ENG"),
            def("Ruben", "Dias", "PT"),
            def("Josko", "Gvardiol", "HR"),
            def("John", "Stones", "ENG"),
            def("Marc", "Guehi", "ENG"),
            def("Nathan", "Ake", "NL"),
            def("Rayan", "Ait-Nouri", "DZ"),
            def("Rico", "Lewis", "ENG"),
            mid("Rodri", "Hernandez", "ES"),
            mid("Mateo", "Kovacic", "HR"),
            mid("Bernardo", "Silva", "PT"),
            mid("Tijjani", "Reijnders", "NL"),
            mid("Phil", "Foden", "ENG"),
            mid("Savinho", "Moreira", "BR"),
            mid("Rayan", "Cherki", "FR"),
            fwd("Erling", "Haaland", "NO"),
            fwd("Omar", "Marmoush", "EG"),
            fwd("Jeremy", "Doku", "BE"),
            fwd("Matheus", "Nunes", "PT"),
            fwd("Nico", "Gonzalez", "ES"),
            fwd("Antoine", "Semenyo", "GH"),
        ],
    },
    TeamTemplate {
        name: "Liverpool",
        short_name: "LIV",
        city: "Liverpool",
        country: "England",
        colors: ("#b91c1c", "#fbbf24"),
        play_style: "HighPress",
        stadium_name: "Anfield",
        roster: &[
            gk("Alisson", "Becker", "BR"),
            gk("Giorgi", "Mamardashvili", "GE"),
            def("Virgil", "van Dijk", "NL"),
            def("Ibrahima", "Konate", "FR"),
            def("Joe", "Gomez", "ENG"),
            def("Andy", "Robertson", "SCO"),
            def("Conor", "Bradley", "NIR"),
            def("Milos", "Kerkez", "HU"),
            def("Jeremie", "Frimpong", "NL"),
            mid("Ryan", "Gravenberch", "NL"),
            mid("Alexis", "Mac Allister", "AR"),
            mid("Dominik", "Szoboszlai", "HU"),
            mid("Florian", "Wirtz", "DE"),
            mid("Wataru", "Endo", "JP"),
            mid("Curtis", "Jones", "ENG"),
            mid("Harvey", "Elliott", "ENG"),
            fwd("Mohamed", "Salah", "EG"),
            fwd("Cody", "Gakpo", "NL"),
            fwd("Alexander", "Isak", "SE"),
            fwd("Hugo", "Ekitike", "FR"),
            fwd("Trey", "Ngumoha", "ENG"),
            fwd("Federico", "Chiesa", "IT"),
        ],
    },
    TeamTemplate {
        name: "Newcastle United",
        short_name: "NEW",
        city: "Newcastle",
        country: "England",
        colors: ("#000000", "#ffffff"),
        play_style: "Counter",
        stadium_name: "St. James' Park",
        roster: &[
            gk("Nick", "Pope", "ENG"),
            gk("Aaron", "Ramsdale", "ENG"),
            def("Kieran", "Trippier", "ENG"),
            def("Lewis", "Hall", "ENG"),
            def("Sven", "Botman", "NL"),
            def("Fabian", "Schar", "CH"),
            def("Malick", "Thiaw", "DE"),
            def("Dan", "Burn", "ENG"),
            def("Valentino", "Livramento", "ENG"),
            mid("Bruno", "Guimaraes", "BR"),
            mid("Sandro", "Tonali", "IT"),
            mid("Joelinton", "Cassio", "BR"),
            mid("Jacob", "Murphy", "ENG"),
            mid("Joe", "Willock", "ENG"),
            mid("Jacob", "Ramsey", "ENG"),
            mid("Emil", "Krafth", "SE"),
            fwd("Yoane", "Wissa", "CD"),
            fwd("Anthony", "Elanga", "SE"),
            fwd("Harvey", "Barnes", "ENG"),
            fwd("Nick", "Woltemade", "DE"),
            fwd("William", "Osula", "DK"),
            fwd("John", "Ruddy", "ENG"),
        ],
    },
    TeamTemplate {
        name: "Real Madrid",
        short_name: "RMA",
        city: "Madrid",
        country: "Spain",
        colors: ("#ffffff", "#d4af37"),
        play_style: "Possession",
        stadium_name: "Estadio Santiago Bernabeu",
        roster: &[
            gk("Thibaut", "Courtois", "BE"),
            gk("Andriy", "Lunin", "UA"),
            def("Dani", "Carvajal", "ES"),
            def("Eder", "Militao", "BR"),
            def("Antonio", "Rudiger", "DE"),
            def("Raul", "Asencio", "ES"),
            def("Dean", "Huijsen", "ES"),
            def("Ferland", "Mendy", "FR"),
            def("Alvaro", "Carreras", "ES"),
            mid("Trent", "Alexander-Arnold", "ENG"),
            mid("Federico", "Valverde", "UY"),
            mid("Aurelien", "Tchouameni", "FR"),
            mid("Eduardo", "Camavinga", "FR"),
            mid("Jude", "Bellingham", "ENG"),
            mid("Arda", "Guler", "TR"),
            mid("Dani", "Ceballos", "ES"),
            fwd("Kylian", "Mbappe", "FR"),
            fwd("Vinicius", "Junior", "BR"),
            fwd("Rodrygo", "Goes", "BR"),
            fwd("Brahim", "Diaz", "MA"),
            fwd("Franco", "Mastantuono", "AR"),
            fwd("Fran", "Garcia", "ES"),
        ],
    },
    TeamTemplate {
        name: "FC Barcelona",
        short_name: "BAR",
        city: "Barcelona",
        country: "Spain",
        colors: ("#9f1239", "#1d4ed8"),
        play_style: "Attacking",
        stadium_name: "Spotify Camp Nou",
        roster: &[
            gk("Marc-Andre", "ter Stegen", "DE"),
            gk("Wojciech", "Szczesny", "PL"),
            def("Jules", "Kounde", "FR"),
            def("Ronald", "Araujo", "UY"),
            def("Pau", "Cubarsi", "ES"),
            def("Andreas", "Christensen", "DK"),
            def("Alejandro", "Balde", "ES"),
            def("Eric", "Garcia", "ES"),
            def("Joao", "Cancelo", "PT"),
            mid("Pedri", "Gonzalez", "ES"),
            mid("Frenkie", "de Jong", "NL"),
            mid("Gavi", "Paez", "ES"),
            mid("Marc", "Casado", "ES"),
            mid("Fermin", "Lopez", "ES"),
            mid("Dani", "Olmo", "ES"),
            mid("Marc", "Bernal", "ES"),
            fwd("Raphinha", "Belloli", "BR"),
            fwd("Lamine", "Yamal", "ES"),
            fwd("Robert", "Lewandowski", "PL"),
            fwd("Ferran", "Torres", "ES"),
            fwd("Marcus", "Rashford", "ENG"),
            fwd("Joan", "Garcia", "ES"),
        ],
    },
    TeamTemplate {
        name: "Bayern Munich",
        short_name: "BAY",
        city: "Munich",
        country: "Germany",
        colors: ("#dc2626", "#1e3a5f"),
        play_style: "HighPress",
        stadium_name: "Allianz Arena",
        roster: &[
            gk("Manuel", "Neuer", "DE"),
            gk("Sven", "Ulreich", "DE"),
            def("Dayot", "Upamecano", "FR"),
            def("Min-jae", "Kim", "KR"),
            def("Jonathan", "Tah", "DE"),
            def("Alphonso", "Davies", "CA"),
            def("Raphael", "Guerreiro", "PT"),
            def("Hiroki", "Ito", "JP"),
            def("Joshua", "Kimmich", "DE"),
            mid("Leon", "Goretzka", "DE"),
            mid("Jamal", "Musiala", "DE"),
            mid("Konrad", "Laimer", "AT"),
            mid("Aleksandar", "Pavlovic", "DE"),
            mid("Tom", "Bischof", "DE"),
            mid("Leroy", "Sane", "DE"),
            mid("Thomas", "Muller", "DE"),
            fwd("Harry", "Kane", "ENG"),
            fwd("Serge", "Gnabry", "DE"),
            fwd("Michael", "Olise", "FR"),
            fwd("Luis", "Diaz", "CO"),
            fwd("Nicolas", "Jackson", "SN"),
            fwd("Mathys", "Tel", "FR"),
        ],
    },
    TeamTemplate {
        name: "Borussia Dortmund",
        short_name: "BVB",
        city: "Dortmund",
        country: "Germany",
        colors: ("#eab308", "#000000"),
        play_style: "Counter",
        stadium_name: "Signal Iduna Park",
        roster: &[
            gk("Gregor", "Kobel", "CH"),
            gk("Alexander", "Meyer", "DE"),
            def("Nico", "Schlotterbeck", "DE"),
            def("Waldemar", "Anton", "DE"),
            def("Niklas", "Sule", "DE"),
            def("Ramy", "Bensebaini", "DZ"),
            def("Julian", "Ryerson", "NO"),
            def("Emre", "Can", "DE"),
            def("Yan", "Couto", "BR"),
            mid("Marcel", "Sabitzer", "AT"),
            mid("Julian", "Brandt", "DE"),
            mid("Felix", "Nmecha", "DE"),
            mid("Jobe", "Bellingham", "ENG"),
            mid("Salih", "Ozcan", "TR"),
            mid("Carney", "Chukwuemeka", "ENG"),
            mid("Daniel", "Svensson", "SE"),
            fwd("Serhou", "Guirassy", "GN"),
            fwd("Karim", "Adeyemi", "DE"),
            fwd("Maximilian", "Beier", "DE"),
            fwd("Fabio", "Silva", "PT"),
            fwd("Patrick", "Drewes", "DE"),
            fwd("Donyell", "Malen", "NL"),
        ],
    },
    TeamTemplate {
        name: "Paris Saint-Germain",
        short_name: "PSG",
        city: "Paris",
        country: "France",
        colors: ("#1e3a5f", "#dc2626"),
        play_style: "Attacking",
        stadium_name: "Parc des Princes",
        roster: &[
            gk("Matvey", "Safonov", "RU"),
            gk("Lucas", "Chevalier", "FR"),
            def("Marquinhos", "Correa", "BR"),
            def("Willian", "Pacho", "EC"),
            def("Ilya", "Zabarnyi", "UA"),
            def("Lucas", "Hernandez", "FR"),
            def("Nuno", "Mendes", "PT"),
            def("Achraf", "Hakimi", "MA"),
            def("Lucas", "Beraldo", "BR"),
            mid("Vitinha", "Ferreira", "PT"),
            mid("Joao", "Neves", "PT"),
            mid("Warren", "Zaire-Emery", "FR"),
            mid("Fabian", "Ruiz", "ES"),
            mid("Kang-in", "Lee", "KR"),
            mid("Senny", "Mayulu", "FR"),
            mid("Desire", "Doue", "FR"),
            fwd("Khvicha", "Kvaratskhelia", "GE"),
            fwd("Bradley", "Barcola", "FR"),
            fwd("Ousmane", "Dembele", "FR"),
            fwd("Goncalo", "Ramos", "PT"),
            fwd("Quentin", "Ndjantou", "FR"),
            fwd("Ibrahim", "Mbaye", "SN"),
        ],
    },
    TeamTemplate {
        name: "Olympique Lyon",
        short_name: "OL",
        city: "Lyon",
        country: "France",
        colors: ("#1d4ed8", "#ffffff"),
        play_style: "Balanced",
        stadium_name: "Groupama Stadium",
        roster: &[
            gk("Dominik", "Greif", "SK"),
            gk("Remy", "Descamps", "FR"),
            def("Nicolas", "Tagliafico", "AR"),
            def("Abner", "Vinicius", "BR"),
            def("Moussa", "Niakhate", "SN"),
            def("Clinton", "Mata", "AO"),
            def("Hans", "Hateboer", "NL"),
            def("Noham", "Kamara", "FR"),
            def("Ainsley", "Maitland-Niles", "ENG"),
            mid("Orel", "Mangala", "BE"),
            mid("Tanner", "Tessmann", "US"),
            mid("Corentin", "Tolisso", "FR"),
            mid("Tyler", "Morton", "ENG"),
            mid("Noah", "Nartey", "DK"),
            mid("Pavel", "Sulc", "CZ"),
            mid("Ruben", "Kluivert", "NL"),
            fwd("Malick", "Fofana", "BE"),
            fwd("Ernest", "Nuamah", "GH"),
            fwd("Rachid", "Ghezzal", "DZ"),
            fwd("Roman", "Yaremchuk", "UA"),
            fwd("Martin", "Satriano", "UY"),
            fwd("Georges", "Mikautadze", "GE"),
        ],
    },
    TeamTemplate {
        name: "AC Milan",
        short_name: "MIL",
        city: "Milan",
        country: "Italy",
        colors: ("#dc2626", "#000000"),
        play_style: "Defensive",
        stadium_name: "Stadio San Siro",
        roster: &[
            gk("Mike", "Maignan", "FR"),
            gk("Lorenzo", "Torriani", "IT"),
            def("Strahinja", "Pavlovic", "RS"),
            def("Fikayo", "Tomori", "ENG"),
            def("Matteo", "Gabbia", "IT"),
            def("Koni", "De Winter", "BE"),
            def("Pervis", "Estupinian", "EC"),
            def("Davide", "Bartesaghi", "IT"),
            def("Theo", "Hernandez", "FR"),
            mid("Youssouf", "Fofana", "FR"),
            mid("Samuele", "Ricci", "IT"),
            mid("Adrien", "Rabiot", "FR"),
            mid("Ardon", "Jashari", "CH"),
            mid("Ruben", "Loftus-Cheek", "ENG"),
            mid("Alexis", "Saelemaekers", "BE"),
            mid("Luka", "Modric", "HR"),
            fwd("Rafael", "Leao", "PT"),
            fwd("Christian", "Pulisic", "US"),
            fwd("Christopher", "Nkunku", "FR"),
            fwd("Santiago", "Gimenez", "MX"),
            fwd("Niclas", "Fullkrug", "DE"),
            fwd("Noah", "Okafor", "CH"),
        ],
    },
    TeamTemplate {
        name: "AS Roma",
        short_name: "ROM",
        city: "Rome",
        country: "Italy",
        colors: ("#eab308", "#7c2d12"),
        play_style: "Counter",
        stadium_name: "Stadio Olimpico",
        roster: &[
            gk("Mile", "Svilar", "RS"),
            gk("Pierluigi", "Gollini", "IT"),
            def("Gianluca", "Mancini", "IT"),
            def("Evan", "Ndicka", "CI"),
            def("Mario", "Hermoso", "ES"),
            def("Daniele", "Ghilardi", "IT"),
            def("Angelino", "Valera", "ES"),
            def("Zeki", "Celik", "TR"),
            def("Devyne", "Rensch", "NL"),
            mid("Bryan", "Cristante", "IT"),
            mid("Manu", "Kone", "FR"),
            mid("Niccolo", "Pisilli", "IT"),
            mid("Lorenzo", "Pellegrini", "IT"),
            mid("Neil", "El Aynaoui", "MA"),
            mid("Bryan", "Zaragoza", "ES"),
            mid("Konstantinos", "Tsimikas", "GR"),
            fwd("Paulo", "Dybala", "AR"),
            fwd("Artem", "Dovbyk", "UA"),
            fwd("Stephan", "El Shaarawy", "IT"),
            fwd("Matias", "Soule", "AR"),
            fwd("Devyne", "Rensch", "NL"),
            fwd("Evan", "Ferguson", "IE"),
        ],
    },
    TeamTemplate {
        name: "Ajax",
        short_name: "AJA",
        city: "Amsterdam",
        country: "Netherlands",
        colors: ("#dc2626", "#ffffff"),
        play_style: "Attacking",
        stadium_name: "Johan Cruijff ArenA",
        roster: &[
            gk("Maarten", "Paes", "NL"),
            gk("Vitezslav", "Jaros", "CZ"),
            def("Youri", "Baas", "NL"),
            def("Josip", "Sutalo", "HR"),
            def("Ko", "Itakura", "JP"),
            def("Owen", "Wijndal", "NL"),
            def("Anton", "Gaaei", "DK"),
            def("Takehiro", "Tomiyasu", "JP"),
            def("Lucas", "Rosa", "BR"),
            mid("Youri", "Regeer", "NL"),
            mid("Kian", "Fitz-Jim", "NL"),
            mid("Davy", "Klaassen", "NL"),
            mid("Jorthy", "Mokio", "BE"),
            mid("Oscar", "Gloukh", "IL"),
            mid("Rayane", "Bounida", "MA"),
            mid("Steven", "Berghuis", "NL"),
            fwd("Mika", "Godts", "BE"),
            fwd("Kasper", "Dolberg", "DK"),
            fwd("Wout", "Weghorst", "NL"),
            fwd("Maher", "Carrizo", "AR"),
            fwd("Oliver", "Edvardsen", "NO"),
            fwd("Donyell", "Malen", "NL"),
        ],
    },
    TeamTemplate {
        name: "Sporting CP",
        short_name: "SCP",
        city: "Lisbon",
        country: "Portugal",
        colors: ("#16a34a", "#ffffff"),
        play_style: "Possession",
        stadium_name: "Estadio Jose Alvalade",
        roster: &[
            gk("Rui", "Silva", "PT"),
            gk("Joao", "Virginia", "PT"),
            def("Ousmane", "Diomande", "CI"),
            def("Goncalo", "Inacio", "PT"),
            def("Zeno", "Debast", "BE"),
            def("Eduardo", "Quaresma", "PT"),
            def("Maxi", "Araujo", "UY"),
            def("Nuno", "Santos", "PT"),
            def("Ivan", "Fresneda", "ES"),
            mid("Morten", "Hjulmand", "DK"),
            mid("Hidemasa", "Morita", "JP"),
            mid("Daniel", "Braganca", "PT"),
            mid("Pedro", "Goncalves", "PT"),
            mid("Francisco", "Trincao", "PT"),
            mid("Geovany", "Quenda", "PT"),
            mid("Geny", "Catamo", "MZ"),
            fwd("Luis", "Suarez", "CO"),
            fwd("Fotis", "Ioannidis", "GR"),
            fwd("Luis", "Guilherme", "BR"),
            fwd("Ricardo", "Mangas", "PT"),
            fwd("Giorgi", "Kochorashvili", "GE"),
            fwd("Souleymane", "Faye", "SN"),
        ],
    },
    TeamTemplate {
        name: "FC Porto",
        short_name: "POR",
        city: "Porto",
        country: "Portugal",
        colors: ("#1d4ed8", "#ffffff"),
        play_style: "Defensive",
        stadium_name: "Estadio do Dragao",
        roster: &[
            gk("Diogo", "Costa", "PT"),
            gk("Claudio", "Ramos", "PT"),
            def("Nehuen", "Perez", "AR"),
            def("Jan", "Bednarek", "PL"),
            def("Thiago", "Silva", "BR"),
            def("Francisco", "Moura", "PT"),
            def("Zaidu", "Sanusi", "NG"),
            def("Alberto", "Costa", "PT"),
            def("Martim", "Fernandes", "PT"),
            mid("Alan", "Varela", "AR"),
            mid("Seko", "Fofana", "CI"),
            mid("Gabri", "Veiga", "ES"),
            mid("Pablo", "Rosario", "NL"),
            mid("Rodrigo", "Mora", "PT"),
            mid("Borja", "Sainz", "ES"),
            mid("Jakub", "Kiwior", "PL"),
            fwd("Samu", "Aghehowa", "ES"),
            fwd("William", "Gomes", "BR"),
            fwd("Terem", "Moffi", "NG"),
            fwd("Luuk", "de Jong", "NL"),
            fwd("Deniz", "Gul", "TR"),
            fwd("Diogo", "Leite", "PT"),
        ],
    },
    TeamTemplate {
        name: "Anderlecht",
        short_name: "AND",
        city: "Brussels",
        country: "Belgium",
        colors: ("#7c3aed", "#fbbf24"),
        play_style: "Balanced",
        stadium_name: "Lotto Park",
        roster: &[
            gk("Colin", "Coosemans", "BE"),
            gk("Justin", "Heekeren", "DE"),
            def("Killian", "Sardella", "BE"),
            def("Marco", "Kana", "BE"),
            def("Mihajlo", "Ilic", "RS"),
            def("Ludwig", "Augustinsson", "SE"),
            def("Moussa", "Diarra", "ML"),
            def("Thomas", "Foket", "BE"),
            def("Ali", "Maamar", "MA"),
            mid("Mats", "Rits", "BE"),
            mid("Yari", "Verschaeren", "BE"),
            mid("Thorgan", "Hazard", "BE"),
            mid("Mario", "Stroeykens", "BE"),
            mid("Anas", "Tajaouart", "MA"),
            mid("Enric", "Llansana", "NL"),
            mid("Nathan", "De Cat", "BE"),
            fwd("Alexis", "Flips", "FR"),
            fwd("Danylo", "Sikan", "UA"),
            fwd("Cesar", "Huerta", "MX"),
            fwd("Ibrahim", "Konate", "ML"),
            fwd("Adriano", "Bertaccini", "BE"),
            fwd("Ilay", "Camara", "SN"),
        ],
    },
];
